FONTOS:

A default billentyuzetkiosztas nem veletlen eredmenye!
A problemamentes jatek csak ezzel garantalt. Ami biztos, hogy elvezhetetlenne
teszi a jatekot, az az, hogyha a crsr billentyukre allitod be az iranyitasodat.

Ime a jo kiosztas:

Jatekos #1:
 
       5
     1   3  (A num. keypad-n)  es RSHIFT(Ez nem minden bill-n muxik.)
       2    
 
Jatekos #2:

	r
      d   g      es    tab
        f



									Remetix